name = "agencia-toro-site"
compatibility_date = "2026-06-17"
compatibility_flags = ["nodejs_compat"]
main = "site/.output/server/index.mjs"

[assets]
directory = "site/.output/public"
binding = "ASSETS"

[vars]
API_URL = "https://api.agenciatoro.com.br"

[observability]
enabled = true
