/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LeadIngestRouteImport } from './routes/lead-ingest'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as IndexRouteImport } from './routes/index'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadIngestRoute = LeadIngestRouteImport.update({
  id: '/lead-ingest',
  path: '/lead-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/lead-ingest': typeof LeadIngestRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/lead-ingest': typeof LeadIngestRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/lead-ingest': typeof LeadIngestRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise'
    | '/lead-ingest'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise'
    | '/lead-ingest'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
  id:
    | '__root__'
    | '/'
    | '/analise'
    | '/lead-ingest'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseRoute: typeof AnaliseRoute
  LeadIngestRoute: typeof LeadIngestRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-ingest': {
      id: '/lead-ingest'
      path: '/lead-ingest'
      fullPath: '/lead-ingest'
      preLoaderRoute: typeof LeadIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseRoute: AnaliseRoute,
  LeadIngestRoute: LeadIngestRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
